//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auditor.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IdentityErrorMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityErrorMessagesResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auditor.Server.Resources.IdentityErrorMessagesResource", typeof(IdentityErrorMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un usuario con esta sesión.
        /// </summary>
        public static string A_user_with_this_login_already_exists_ {
            get {
                return ResourceManager.GetString("A user with this login already exists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error inesperado.
        /// </summary>
        public static string An_unknown_failure_has_occurred_ {
            get {
                return ResourceManager.GetString("An unknown failure has occurred.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email {0} ya ha sido tomado.
        /// </summary>
        public static string Email__0__is_already_taken_ {
            get {
                return ResourceManager.GetString("Email {0} is already taken.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email {0} no es válido..
        /// </summary>
        public static string Email__0__is_invalid_ {
            get {
                return ResourceManager.GetString("Email {0} is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta.
        /// </summary>
        public static string Incorrect_password_ {
            get {
                return ResourceManager.GetString("Incorrect password.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a token no válido.
        /// </summary>
        public static string Invalid_token_ {
            get {
                return ResourceManager.GetString("Invalid token.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El desbloqueo no esta activado para este usuario.
        /// </summary>
        public static string Lockout_is_not_enabled_for_this_user_ {
            get {
                return ResourceManager.GetString("Lockout is not enabled for this user.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener almenos {0} caracteres..
        /// </summary>
        public static string Passwords_must_be_at_least__0__characters_ {
            get {
                return ResourceManager.GetString("Passwords must be at least {0} characters.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos un dígito (&apos;0&apos;-&apos;9&apos;).
        /// </summary>
        public static string Passwords_must_have_at_least_one_digit___0___9___ {
            get {
                return ResourceManager.GetString("Passwords must have at least one digit (\'0\'-\'9\').", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos una minúscula (&apos;a&apos;-&apos;z&apos;).
        /// </summary>
        public static string Passwords_must_have_at_least_one_lowercase___a___z___ {
            get {
                return ResourceManager.GetString("Passwords must have at least one lowercase (\'a\'-\'z\').", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos un caracter no alfanumérico.
        /// </summary>
        public static string Passwords_must_have_at_least_one_non_alphanumeric_character_ {
            get {
                return ResourceManager.GetString("Passwords must have at least one non alphanumeric character.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña debe tener al menos una mayúscula (&apos;A&apos;-&apos;Z&apos;).
        /// </summary>
        public static string Passwords_must_have_at_least_one_uppercase___A___Z___ {
            get {
                return ResourceManager.GetString("Passwords must have at least one uppercase (\'A\'-\'Z\').", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rol {0} ya está tomado..
        /// </summary>
        public static string Role_name__0__is_already_taken_ {
            get {
                return ResourceManager.GetString("Role name {0} is already taken.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de rol {0} no es válido.
        /// </summary>
        public static string Role_name__0__is_invalid_ {
            get {
                return ResourceManager.GetString("Role name {0} is invalid.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya tiene una contraseña asignada.
        /// </summary>
        public static string User_already_has_a_password_set_ {
            get {
                return ResourceManager.GetString("User already has a password set.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya está en el role de {0}.
        /// </summary>
        public static string User_already_in_role__0__ {
            get {
                return ResourceManager.GetString("User already in role {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no está en el role {0}.
        /// </summary>
        public static string User_is_not_in_role__0__ {
            get {
                return ResourceManager.GetString("User is not in role {0}.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario {0} ya está tomado.
        /// </summary>
        public static string User_Name__0__is_already_taken_ {
            get {
                return ResourceManager.GetString("User Name {0} is already taken.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre se usuario {0} no es válido, solo puede contener letras y números..
        /// </summary>
        public static string User_name__0__is_invalid__can_only_contain_letters_or_digits_ {
            get {
                return ResourceManager.GetString("User name {0} is invalid, can only contain letters or digits.", resourceCulture);
            }
        }
    }
}
